config/routes.rb
Decorist::Application.routes.draw do
  get "order/cart", as: "cart"
  get "order/payment", as: "payment"
  post "order/payment"
  get "order/info", as: "info"
  root to: "order#cart"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
 skip_before_action :verify_authenticity_token
  def cart
  end

  def payment
  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Decorist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="hero-unit">
		<h1 class="title">COMPLETE YOUR ORDER</br>
		<small><i>Making interior design personal, affordable and easy</i></small></h1>
	</div>		
<%= yield %>
</div>
</body>
</html>

app/views/order/cart.html.erb
<hr/>
<div class="row-fluid text-center">
	<div class="col-md-4">
		<span class="round active-page">1</span>
		<span>View Cart</span>
	</div>
	<div class="col-md-4 inactive-page">
	<%= link_to '2', payment_path, class: "round" %>
		<span>Payment</span>
	</div>
	<div class="col-md-4 inactive-page">
		<%= link_to '3', info_path, class: "round" %>
		<span>Additional info</span>
	</div>
</div>

	<div class="row-fluid">
		<section class="col-sm-8">
			<header><i>Your Shopping Cart</i>&nbsp;&nbsp;<span><a href="#" class="happiness">CONTINUE SHOPPING</a></span></header>
			<table class="table">
				<thead>
					<tr>
						<th>Item</th>
						<th>Quantity</th>
						<th>Price</th>
						<th>Change</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td id="item"><%= image_tag('2.png') %>PERSONAL SHOPPER PACKAGE</td>
						<td id="quantity"><span class="glyphicon glyphicon-minus-sign minus"></span>
						<input id="num" type="text" value="1"/>
						<span class="glyphicon glyphicon-plus-sign plus"></span>
						</td>
						<td class="cell">$<span id="price">69.00</span></td>
						<td class="cell"><span class="glyphicon glyphicon-remove-sign remove"></span><span class="remove">REMOVE</span></td>
					</tr>
				</tbody>
			</table>
			<div id="stats">
			<span id="promo">
				<a href="#" id="add">ADD PROMO CODE</a>
			</span>
				<table class="table borderless">
					<tbody class="pull-right">
						<tr>
							<td>SUBTOTAL</td><td>$<span class="sub">69.00</span></td>
						</tr>
						<tr>
							<td>TAX</td><td>$0.00</td>
						</tr>
						<tr>
							<td>SHIPPING</td><td>$0.00</td>
						</tr>
						<tr><td>TOTAL</td><td>$<span class="sub">69.00</span></td></tr>
					</tbody>
				</table>
			</div>
			<p class="pull-right">
			  <a href="#" class="happiness" data-toggle="modal" data-target="#myModal">HAPPINESS GARANTEE!</a>
			  <%= link_to payment_path do %>
			  <button type="button" class="btn btn-primary button">NEXT-PAYMENT</button>
			  <% end %>
			</p>
			<!-- Modal -->
					<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					  <div class="modal-dialog">
					    <div class="modal-content">
					      <div class="modal-body">
					      <legend class="title">HAPPINESS GUARANTEE</legend>
					      <h2 class="popup_header"><i>Our Promise to You</i></h2>
					      <p class="popup_content text-muted">Decorist is all about you. When you order a designer service one of our experienced designers will review your profile, questionnaire, photos and anything else you have provided. They will develop a recomendation that is personal - one that reflects your lyfestyle, style and budget.
					      <br><br>
					      We really want you to love your recommendations and use them to transform your space. If you are not delighted with your recommendations please email us and we will make it right. We will work to make sure you get recommendations that make you, and your room, happy so you can fall in love with your home all over again.</p>
					      <h2 class="popup_header"><i>About Decorist Designers</i></h2>
					      <p class="popup_content text-muted">Decorist designers are carefully selected for their ability to deliver great recommendations that reflect your style and budget. Our designers know which products work, how to pull a look together quickly and easily with a focus on key elements that will give you the most bang for your buck. Their product recommendations are made without consideration of any product commissions - all recommendations are based on what the designer thinks will look great and work for your space based on experience -- period.</p>
					      </div>
					     
					    </div>
					  </div>
					</div>
					
		</section>
		<aside class="col-sm-4">
			 <%= image_tag('image-1.png') %>
		</aside>
	</div>

app/views/order/info.html.erb
<hr/>
<div class="row-fluid text-center clearfix">
	<div class="col-md-4 inactive-page">
	<%= link_to '1', cart_path, class: "round" %>
		<span>View Cart</span>
	</div>
	<div class="col-md-4 inactive-page">
	<%= link_to '2', payment_path, class: "round" %>
		<span>Payment</span>
	</div>
	<div class="col-md-4">
		<span class="round active-page">3</span>
		<span>Additional info</span>
	</div>
</div>
<div id="status-box">
	<h1 id="status-header">CONGRATS! YOUR ORDER HAS BEEN PROCESSED</h1>
	<p id="status-content"><i>To get your advice please complete the form below. This can be done now or you can return to it later.</i></p>
</div>

<div class="row-fluid">
	<section class="col-sm-8">
	<div class="info">
    	<legend class="italic-header"><i>Basic Information</i></legend>
    </div>
    	<form id="basic-info" class="form-inline" role="form">
    	<p>I am looking for a <input id="prod" type="text" class="form-control input-size" placeholder="product (ex. chair, sofa)" required> for my <input id="room" type="text" class="form-control input-size-big" placeholder="room (ex. living room, bedroom)" required> in <input id="color" type="text" class="form-control input-size" placeholder="color or materials" required> and my budget is <input id="budget" type="text" class="form-control input-size" placeholder="price (ex.$500)" required>.</p>
    	<p class="add-info">ANY ADDITIONAL INFORMATION SHARE HELPS US GIVE THE BEST RECOMMENDATIONS</p>
		<textarea id="add-info" class="form-control form" rows="4" cols="45" placeholder="Helpful information would be approximate dimensions of the product you're looking for, other items your planning on replacing in your room, materials you prefer, materials or colors you like or do not like, etc." required>
		</textarea>

		<legend id="photos" class="italic-header"><i>Upload Photos</i></legend>
		<p class="small-font">The best photos capture the key features of the room (main furniture, layout, room features) from 2 or 3 corners of the room. Capture key colors, textures and patterns that you want to keep.</p>
	<div id="upload-form">
		<span class="glyphicon glyphicon-picture"></span><br>
		DRAG AND DROP PHOTOS HERE<br>
		OR <label for="files" class="blue-links upload">SELECT FILE TO UPLOAD<input type="file" id="files" class="hidden"></label>
	</div>

		<legend id="photos" class="italic-header"><i>Additional Information <span class="text-muted">(Optional)</span></i></legend>
		<p class="add-info">PASTE A URL FOR A PINTEREST BOARD, HOUZZ IDEA BOOK OR OTHER WEBSITE</p>
		<input type="url" class="form-control input-size-big">
		<p class="add-info">SHARE ONE OF YOUR DECORIST DESIGN BOARD</p>
		<button type="button" class="btn btn-primary button blue-links gray">ATTACH DECORIST DESIGN BOARD</button>
		<div>
		<p class="pull-right">
		  <button type="button" class="btn btn-primary button blue-links gray">SAVE DRAFT</button>
		  <button type="submit button" data-toggle="modal" data-target=".bs-example-modal-lg" class="btn btn-primary button" id="designer">SEND TO DESIGNER</button>
		</p>
		</div>
		</form>
		</section>
		<!-- Modal -->
					<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  						<div class="modal-dialog modal-lg">
    					<div class="modal-content">
					      <div class="modal-body">
					      <p class="title final">THANKS! YOUR PERSONAL SHOPPER WILL START SHOPPING!</p>
					      <h2 class="popup_header"><i>You will recieve an email with a link to your shopping solution <br> in 5 business days!</i></h2>
					      <button type="button" class="btn btn-primary btn-block button">SHOP PERSONALIZED FINDS</button>
					      </div>
					    </div>
					  </div>
					</div>
		
		<aside class="col-sm-4">
			 <%= image_tag('image-1.png') %>
		</aside>
</div>

app/views/order/payment.html.erb
<hr/>
<div class="row-fluid text-center">
	<div class="col-md-4 inactive-page">
	<%= link_to '1', cart_path, class: "round" %>
		<span>View Cart</span>
	</div>
	<div class="col-md-4">
		<span class="round active-page">2</span>
		<span>Payment</span>
	</div>
	<div class="col-md-4 inactive-page">
	<%= link_to '3', info_path, class: "round", id: "info-page" %>
		<span>Additional info</span>
	</div>
</div>

<div class="row-fluid">
	<section class="col-sm-8">
		<legend class="italic-header"><i>Your Billing Information</i></legend>
		<form method="post" role="form" class="form-group" id="form-font">
		<div id="full-name">
			<div class="name">
			<label class="control-label">FIRST NAME</label>
			<input type="text" class="form-control" required>
			</div>
			<div class="name">
			<label class="control-label">LAST NAME</label>
			<input type="text" class="form-control" required>
			</div>
		</div>

		<div id="zip-code">
			<label class="control-label">ZIP CODE</label>
			<input type="number" class="form-control" required>
		</div>

		<div id="card-number">
			<label class="control-label">CARD NUMBER</label>
			<input type="number" class="form-control" required>
		</div>

		<div id="exp-date">
		<div>
		    <label class="control-label">Expiration Date</label>
		    <div id="date-option">
		      <select>
		        <option value="" selected>01</option>
		        <option value="02">02</option>
		        <option value="03">03</option>
		        <option value="04">04</option>
		        <option value="05">05</option>
		        <option value="06">06</option>
		        <option value="07">07</option>
		        <option value="08">08</option>
		        <option value="09">09</option>
		        <option value="10">10</option>
		        <option value="11">11</option>
		        <option value="12">12</option>
		      </select>
		      <select>
		        <option value="" selected>2014</option>
		        <option value="15">2015</option>
		        <option value="16">2016</option>
		        <option value="17">2017</option>
		        <option value="18">2018</option>
		        <option value="19">2019</option>
		        <option value="20">2020</option>
		      </select>
		      </div>
		 </div>
		 <div id="cvv">
			    <label class="control-label">CVV</label>
			    <input type="text" class="form-control" required>
		  </div>
		  </div>
		  <br>
		  <div id="checkbox">
		  <input id="save-card" type="checkbox" checked="checked"><label for="save-card">SAVE CARD FOR FUTURE USE</label>
		  </div>
		  <legend></legend>
		<p class="pull-right">
		  <a href="#" class="happiness" data-toggle="modal" data-target="#myModal">HAPPINESS GARANTEE!</a>
		  <%= link_to info_path do %>
		  <button type="submit" id="place-order" class="btn btn-primary button">PLACE ORDER</button>
		  <% end %>
		</p>
		</form>
		</section>
		<!-- Modal -->
					<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					  <div class="modal-dialog">
					    <div class="modal-content">
					      <div class="modal-body">
					      <legend class="title">HAPPINESS GUARANTEE</legend>
					      <h2 class="popup_header"><i>Our Promise to You</i></h2>
					      <p class="popup_content text-muted">Decorist is all about you. When you order a designer service one of our experienced designers will review your profile, questionnaire, photos and anything else you have provided. They will develop a recomendation that is personal - one that reflects your lyfestyle, style and budget.
					      <br><br>
					      We really want you to love your recommendations and use them to transform your space. If you are not delighted with your recommendations please email us and we will make it right. We will work to make sure you get recommendations that make you, and your room, happy so you can fall in love with your home all over again.</p>
					      <h2 class="popup_header"><i>About Decorist Designers</i></h2>
					      <p class="popup_content text-muted">Decorist designers are carefully selected for their ability to deliver great recommendations that reflect your style and budget. Our designers know which products work, how to pull a look together quickly and easily with a focus on key elements that will give you the most bang for your buck. Their product recommendations are made without consideration of any product commissions - all recommendations are based on what the designer thinks will look great and work for your space based on experience -- period.</p>
					      </div>
					    </div>
					  </div>
					</div>
		<aside class="col-sm-4">
			 <%= image_tag('image-1.png') %>
		</aside>
	</div>